import { app, BrowserWindow, ipcMain } from 'electron';
import { DatabaseService } from './database';
import { registerGameHandlers } from './ipc/gameHandlers';
import { registerPlayerHandlers } from './ipc/playerHandlers';
import { registerHistoryHandlers } from './ipc/historyHandlers';
import { registerStatisticsHandlers } from './ipc/statisticsHandlers';
import { registerSettingsHandlers } from './ipc/settingsHandlers';
import { registerExportImportHandlers } from './ipc/exportImportHandlers';
import { ShortcutsService } from './services/ShortcutsService';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Register keyboard shortcuts after window is ready
  mainWindow.webContents.once('did-finish-load', () => {
    const shortcutsService = ShortcutsService.getInstance();
    shortcutsService.setMainWindow(mainWindow);
    shortcutsService.registerShortcuts();
  });

  // Cleanup when window is closed
  mainWindow.on('closed', () => {
    // Clean up shortcuts service
    ShortcutsService.getInstance().setMainWindow(null);
  });
};

// IPC Handlers
ipcMain.handle('app:quit', () => {
  // Unregister shortcuts
  ShortcutsService.getInstance().unregisterShortcuts();
  // Close database connection before quitting
  DatabaseService.getInstance().close();
  app.quit();
});

// Handle shortcuts toggle
ipcMain.handle('shortcuts:toggle', (_event, enabled: boolean) => {
  const shortcutsService = ShortcutsService.getInstance();
  shortcutsService.toggleShortcuts(enabled);
});

// Register game-related IPC handlers
registerGameHandlers();

// Register player-related IPC handlers
registerPlayerHandlers();

// Register history-related IPC handlers
registerHistoryHandlers();

// Register statistics-related IPC handlers
registerStatisticsHandlers();

// Register settings-related IPC handlers
registerSettingsHandlers();

// Register export/import-related IPC handlers
registerExportImportHandlers();

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  // Initialize the database
  const db = DatabaseService.getInstance();
  console.log('Database initialized at:', db.getDatabasePath());

  // Create the window
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    // Unregister shortcuts
    ShortcutsService.getInstance().unregisterShortcuts();
    // Close database connection before quitting
    DatabaseService.getInstance().close();
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
